In [43]:
import numpy as np

dominos = [np.array([[i],[i]]) for i in range(1,31)]
triominos = [np.array([[i,0],[i,i]]) for i in range(1,21)]

pentnominos = [np.array([[0,1,1],
                   [1,1,0],
                   [0,1,0]]),
        np.array([[2],
                  [2],
                  [2],
                  [2],
                  [2]]),
        np.array([[3,0],
                  [3,0],
                  [3,0],
                  [3,3]]),
        np.array([[0,4],
                  [0,4],
                  [4,4],
                  [4,0]]),
        np.array([[5,5],
                  [5,5],
                  [5,0]]),
        np.array([[6,6,6],
                  [0,6,0],
                  [0,6,0]]),
        np.array([[7,0,7], 
                  [7,7,7]]),
        np.array([[8,0,0], 
                  [8,0,0],
                  [8,8,8]]),
        np.array([[9,0,0],
                  [9,9,0],
                  [0,9,9]]),
        np.array([[0,10,0],
                  [10,10,10],
                  [0,10,0]]),
        np.array([[0,11],
                  [11,11],
                  [0,11],
                  [0,11]]),
        np.array([[12,12,0],
                  [0,12,0],
                  [0,12,12]])]

### print(dominos)
### print(triominos)
### print(pentnominos)

In [2]:
board_6x10 = np.ones((6,10))
board_5x12 = np.ones((5,12))
board_3x20 = np.ones((3,20))

board_t=board_6x10
print(board_t)
###print(np.array(board_t))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [4]:
print(board_6x10.shape)

(6, 10)


In [3]:
p = pentnominos[2]
print(pentnominos[2])

[[3 0]
 [3 0]
 [3 0]
 [3 3]]


In [15]:
i,j = 1,2
print(i,j)
print(i)

1 2
1


In [14]:
for i in range(4):
    print(i)

0
1
2
3


In [46]:
def getMutations(pent):
    mutations = [] # use a set to avoid add reduplicated numpy mutation
    mutation = tuple(pent)
    rotation_num = 4 # rot90° while in a 2-D plane 360°/90° = 4
    flip_num = 2 # Two possible flipping trials with flip 180°

    i=0
    while i<rotation_num:
        j = 0
        while j<flip_num:
            mutations.append(mutation) # add first to add the original pent
            mutation = np.flip(mutation)
            j += 1
        mutation = np.rot90(mutation)
        i += 1
    return mutations

In [48]:
getMutations(p)

<class 'tuple'>


[(array([3, 0]), array([3, 0]), array([3, 0]), array([3, 3])), array([[3, 3],
        [0, 3],
        [0, 3],
        [0, 3]]), array([[0, 0, 0, 3],
        [3, 3, 3, 3]]), array([[3, 3, 3, 3],
        [3, 0, 0, 0]]), array([[3, 3],
        [0, 3],
        [0, 3],
        [0, 3]]), array([[3, 0],
        [3, 0],
        [3, 0],
        [3, 3]]), array([[3, 3, 3, 3],
        [3, 0, 0, 0]]), array([[0, 0, 0, 3],
        [3, 3, 3, 3]])]

In [51]:
print(tuple(p))
print(p)

(array([3, 0]), array([3, 0]), array([3, 0]), array([3, 3]))
[[3 0]
 [3 0]
 [3 0]
 [3 3]]


In [86]:
'''
Function getMutation
Input: A pent
Output: A list contain all of the possible mutations by flipping and rotation of a pent
        with the relative coordinates of each squares
'''
def getMutations(pent):
    mutations = set() # use a set to avoid add reduplicated numpy mutation
    mutation = pent
    rotation_num = 4 # rot90° while in a 2-D plane 360°/90° = 4
    flip_num = 2 # Two possible flipping trials with flip 180°

    i=0
    while i<rotation_num:
        j = 0
        while j<flip_num:
            Tran_mutation = getSingleMutation(mutation)
            mutations.add(Tran_mutation) # add first to add the original pent
            mutation = np.flip(mutation,j-1)
            ### print("mutation is",mutation)
            j += 1
        mutation = np.rot90(mutation)
        i += 1
    return list(mutations)

'''
Function getSingleMutation
Input: A mutation
Output: A tuple contain one mutations by flipping or rotation of a pent
        with the relative coordinates of each squares
'''
def getSingleMutation(mutation):
    coords = tuple() # use tuple to avoid np error in add
    for x, y in np.ndindex(mutation.shape):
        if mutation[x][y] != 0:
            coords += ((x, y),)

    origin = coords[0] # Define the origin pos of the mutation to calculate the other squares' coordinates

    for coord in coords:
        if coord[1] < origin[1]:
            origin = coord
        elif coord[1] == origin[1] and coord[0] < origin[0]:
            origin = coord

    TranMutation = tuple()
    for coord in coords:
        TranMutation += ((coord[0] - origin[0], coord[1] - origin[1]),)

    return tuple(sorted(TranMutation)) 


In [84]:
getMutations(p)

[((-3, 1), (-2, 1), (-1, 1), (0, 0), (0, 1)),
 ((0, 0), (0, 1), (1, 0), (2, 0), (3, 0)),
 ((0, 0), (0, 1), (0, 2), (0, 3), (1, 0)),
 ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)),
 ((0, 0), (1, 0), (1, 1), (1, 2), (1, 3)),
 ((0, 0), (0, 1), (1, 1), (2, 1), (3, 1)),
 ((0, 0), (0, 1), (0, 2), (0, 3), (1, 3)),
 ((-1, 3), (0, 0), (0, 1), (0, 2), (0, 3))]

In [90]:
pentnominos = [np.array([[0,1,1],
                   [1,1,0],
                   [0,1,0]]),
        np.array([[2],
                  [2],
                  [2],
                  [2],
                  [2]]),
        np.array([[3,0],
                  [3,0],
                  [3,0],
                  [3,3]]),
        np.array([[0,4],
                  [0,4],
                  [4,4],
                  [4,0]]),
        np.array([[5,5],
                  [5,5],
                  [5,0]]),
        np.array([[6,6,6],
                  [0,6,0],
                  [0,6,0]]),
        np.array([[7,0,7], 
                  [7,7,7]]),
        np.array([[8,0,0], 
                  [8,0,0],
                  [8,8,8]]),
        np.array([[9,0,0],
                  [9,9,0],
                  [0,9,9]]),
        np.array([[0,10,0],
                  [10,10,10],
                  [0,10,0]]),
        np.array([[0,11],
                  [11,11],
                  [0,11],
                  [0,11]]),
        np.array([[12,12,0],
                  [0,12,0],
                  [0,12,12]])]

In [87]:
def getPTypeAndLable(pent):
    PLabel, PType = 0, 0
    for row in range(pent.shape[0]):
        for col in range(pent.shape[1]):
            if pent[row][col] != 0:
                PType += 1
                if PLabel == 0:
                    PLabel = pent[row][col]
    return PType, PLabel

In [89]:
type(getPTypeAndLable(p))

tuple

In [94]:
pents = pentnominos
pents_mutations = {}
p_type = 0 # (2/3/5) the number of squares that some pent is made by 
p_label = 0 # for pento:1-12
for pent in pents:
    p_type, p_label = getPTypeAndLable(pent)
    pents_mutations[p_type,p_label] = getMutations(pent)
print(pents_mutations)

{(5, 1): [((0, 0), (0, 1), (1, 1), (1, 2), (2, 1)), ((0, 0), (1, 0), (1, 1), (1, 2), (2, 1)), ((-1, 1), (0, 0), (0, 1), (1, 1), (1, 2)), ((-1, 2), (0, 0), (0, 1), (0, 2), (1, 1)), ((-1, 1), (-1, 2), (0, 0), (0, 1), (1, 1)), ((-1, 1), (0, 0), (0, 1), (0, 2), (1, 0)), ((-1, 1), (0, 0), (0, 1), (0, 2), (1, 2)), ((-2, 1), (-1, 1), (-1, 2), (0, 0), (0, 1))], (5, 2): [((0, 0), (0, 1), (0, 2), (0, 3), (0, 4)), ((0, 0), (1, 0), (2, 0), (3, 0), (4, 0))], (5, 3): [((-3, 1), (-2, 1), (-1, 1), (0, 0), (0, 1)), ((0, 0), (0, 1), (1, 0), (2, 0), (3, 0)), ((0, 0), (0, 1), (0, 2), (0, 3), (1, 0)), ((0, 0), (1, 0), (2, 0), (3, 0), (3, 1)), ((0, 0), (1, 0), (1, 1), (1, 2), (1, 3)), ((0, 0), (0, 1), (1, 1), (2, 1), (3, 1)), ((0, 0), (0, 1), (0, 2), (0, 3), (1, 3)), ((-1, 3), (0, 0), (0, 1), (0, 2), (0, 3))], (5, 4): [((-2, 1), (-1, 1), (0, 0), (0, 1), (1, 0)), ((-1, 1), (0, 0), (0, 1), (1, 0), (2, 0)), ((0, 0), (1, 0), (2, 0), (2, 1), (3, 1)), ((-1, 2), (-1, 3), (0, 0), (0, 1), (0, 2)), ((-1, 1), (-1, 2),